const fs = require('fs');
const path = require('path');

async function vcfCommand(sock, chatId, message) {
    try {
        // Check if it's a group
        if (!chatId.endsWith('@g.us')) {
            await sock.sendMessage(chatId, {
                text: '╭╺╼━━─━■■━━─━╾╸\n┣⬣ VCF EXPORTER\n┣➤ This command works only in groups\n╰━━━━━━━━━━━━━━━━━━━━⬣\n\n> DARK EMPIRE TECH'
            }, { quoted: message });
            return;
        }

        await sock.sendMessage(chatId, {
            text: '╭╺╼━━─━■■━━─━╾╸\n┣⬣ VCF GENERATION\n┣➤ Fetching group contacts...\n╰━━━━━━━━━━━━━━━━━━━━⬣'
        }, { quoted: message });

        // Get group metadata
        const groupMetadata = await sock.groupMetadata(chatId);
        const participants = groupMetadata.participants;
        
        // Generate VCF content
        let vcfContent = '';
        let contactCount = 0;

        for (const participant of participants) {
            const jid = participant.id;
            const phoneNumber = jid.split('@')[0];
            const name = participant.name || participant.notify || `User_${phoneNumber}`;
            
            // Generate VCF entry
            vcfContent += `BEGIN:VCARD\n`;
            vcfContent += `VERSION:3.0\n`;
            vcfContent += `FN:${name}\n`;
            vcfContent += `TEL;TYPE=CELL:+${phoneNumber}\n`;
            vcfContent += `END:VCARD\n\n`;
            
            contactCount++;
        }

        if (contactCount === 0) {
            await sock.sendMessage(chatId, {
                text: '╭╺╼━━─━■■━━─━╾╸\n┣⬣ NO CONTACTS\n┣➤ No contacts found in group\n╰━━━━━━━━━━━━━━━━━━━━⬣\n\n> DARK EMPIRE TECH'
            }, { quoted: message });
            return;
        }

        // Create temp file
        const tempDir = path.join(__dirname, '../temp');
        if (!fs.existsSync(tempDir)) {
            fs.mkdirSync(tempDir, { recursive: true });
        }

        const fileName = `contacts_${Date.now()}.vcf`;
        const filePath = path.join(tempDir, fileName);
        
        fs.writeFileSync(filePath, vcfContent);

        // Send VCF file
        await sock.sendMessage(chatId, {
            document: fs.readFileSync(filePath),
            fileName: `group_contacts_${groupMetadata.subject.replace(/[^a-zA-Z0-9]/g, '_')}.vcf`,
            caption: `╭╺╼━━─━■■━━─━╾╸\n┣⬣ VCF EXPORT COMPLETE\n┣➤ Group: ${groupMetadata.subject}\n┣➤ Contacts: ${contactCount}\n┣➤ File: Import to phone contacts\n╰━━━━━━━━━━━━━━━━━━━━⬣\n\nGenerated by KNOX MD\n> DARK EMPIRE TECH`,
            mimetype: 'text/vcard'
        });

        // Cleanup
        fs.unlinkSync(filePath);

    } catch (error) {
        console.log('VCF error:', error);
        await sock.sendMessage(chatId, {
            text: `╭╺╼━━─━■■━━─━╾╸\n┣⬣ VCF EXPORT FAILED\n┣➤ Error: ${error.message}\n╰━━━━━━━━━━━━━━━━━━━━⬣\n\n> DARK EMPIRE TECH`
        }, { quoted: message });
    }
}

module.exports = vcfCommand;